version: 0.2

env:
  parameter-store:
    GITHUB_PERSONAL_ACCESS_TOKEN: /clouddefense/git_private_token
phases:
  pre_build:
    commands:
      - echo "Docker information"
      - docker info
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=staging_${COMMIT_HASH:=latest}
      - GITHUB_BRANCH_NAME="${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}"
      # - GITHUB_REPO_URL="https://${GITHUB_PERSONAL_ACCESS_TOKEN}@${CODEBUILD_SOURCE_REPO_URL#https://}"
      - GITHUB_REPO_URL="${CODEBUILD_SOURCE_REPO_URL}"
      - echo $GITHUB_REPO_URL
      - echo $IMAGE_TAG
      - echo $GITHUB_BRANCH_NAME
      - echo end of pre_build phase
  build:
    commands:
      - echo Build started on `date`
      - echo "Replace robots.txt with environment version"
      - |
        if [ "$ECS_CLUSTER_NAME" = "ProductionCluster" ]; then
          cp absi/templates/robots.prod absi/templates/robots.txt
        else
          cp absi/templates/robots.staging absi/templates/robots.txt
        fi
        cat absi/templates/robots.txt
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Start Running tests"
      - docker run --rm -e DEBUG=True -e SECRET_KEY=secret_test_key $REPOSITORY_URI:latest python manage.py test
      - echo "Pushing the Docker images..."
      - echo docker image latest - $REPOSITORY_URI:latest
      - echo docker image git tag - $REPOSITORY_URI:$IMAGE_TAG 
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"$ECS_CONTAINER_NAME","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Retrieve the latest task definition ARN..."
      - |
        latest_arn=$(aws ecs list-task-definitions \
            --family-prefix $ECS_TASK_DEFINITION_FAMILY \
            --status ACTIVE \
            --sort DESC \
            --no-paginate \
            --query 'taskDefinitionArns[0]' \
            --output text)

      - echo "Latest ARN:" $latest_arn
      - echo "Describe the latest task definition and save the JSON to a file..."
      - aws ecs describe-task-definition --task-definition $latest_arn --query 'taskDefinition' --output json > previous-task-definition.json
      - echo "Below jq command to remove the warnings from github because the properties are not needed for the ECS deploy..."
      - jq 'del(.compatibilities, .taskDefinitionArn, .requiresAttributes, .revision, .status, .registeredAt, .registeredBy)' previous-task-definition.json > tmpfile && mv tmpfile previous-task-definition.json
      - echo "Modify the JSON to update the image..."
      - jq --arg image "$REPOSITORY_URI:$IMAGE_TAG" '.containerDefinitions[0].image = $image' previous-task-definition.json > task-definition.json      
      - echo "Run aws ecs register task definition..."
      - TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json file://task-definition.json --query "taskDefinition.taskDefinitionArn" --output text)
      - echo "Registered new task definition - $TASK_DEFINITION_ARN"
      - echo "Updating Staging ECS service"
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $TASK_DEFINITION_ARN
artifacts:
    files: imagedefinitions.json
