# Generated by Django 6.0.4 on 2026-04-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Arabic text to play and evaluate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
