# Generated by Django 6.0.5 on 2026-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playblock',
            name='diacritic',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playblock',
            name='final',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playblock',
            name='initial',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playblock',
            name='medial',
            field=models.CharField(blank=True, null=True),
        ),
    ]
