# Generated by Django 6.0.6 on 2026-07-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_playblock_diacritic_playblock_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleOverviewBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
