# Generated by Django 6.0.6 on 2026-07-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_moduleoverviewblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOverviewBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
