# Generated by Django 6.0.8 on 2026-08-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playblock',
            name='final_ipa',
            field=models.CharField(blank=True, help_text='IPA notation for final examples', null=True),
        ),
        migrations.AddField(
            model_name='playblock',
            name='initial_ipa',
            field=models.CharField(blank=True, help_text='IPA notation for initial examples', null=True),
        ),
        migrations.AddField(
            model_name='playblock',
            name='medial_ipa',
            field=models.CharField(blank=True, help_text='IPA notation for medial examples', null=True),
        ),
        migrations.AlterField(
            model_name='playblock',
            name='final',
            field=models.CharField(blank=True, help_text='Word examples for final position', null=True),
        ),
        migrations.AlterField(
            model_name='playblock',
            name='initial',
            field=models.CharField(blank=True, help_text='Word examples for initial position', null=True),
        ),
        migrations.AlterField(
            model_name='playblock',
            name='medial',
            field=models.CharField(blank=True, help_text='Word examples for medial position', null=True),
        ),
    ]
