# Generated by Django 6.1.2 on 2026-10-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_playblock_final_ipa_playblock_initial_ipa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playblock',
            name='final_english',
            field=models.CharField(blank=True, help_text='English translations for final examples', null=True),
        ),
        migrations.AddField(
            model_name='playblock',
            name='initial_english',
            field=models.CharField(blank=True, help_text='English translations for initial examples', null=True),
        ),
        migrations.AddField(
            model_name='playblock',
            name='medial_english',
            field=models.CharField(blank=True, help_text='English translations for medial examples', null=True),
        ),
    ]
